resource "kubernetes_config_map" "ac_dl_ingest" {
  metadata {
    name      = "ac-dl-ingest"
    namespace = "uat01"

    labels = {
      app = "ac-dl-ingest"
    }
  }

  data = {
    "lineage.cql" = "CREATE KEYSPACE IF NOT EXISTS ops360uat01_lineage WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};\nCREATE TABLE ops360uat01_lineage.attribute_change (\n    object_id text,\n    attribute_id text,\n    applies_at timestamp,\n    recorded_on timestamp,\n    extra_keys text,\n    datamodel_id text,\n    class_id text,\n    lineage text,\n    lineage_addition text,\n    transaction_id text,\n    process_id text,\n    source_id bigint,\n    source_name text,\n    user_id text,\n    comment text,\n    caused_by_changes text,\n    PRIMARY KEY ((object_id, attribute_id), applies_at, recorded_on, extra_keys)\n)\nWITH CLUSTERING ORDER BY (applies_at DESC, recorded_on DESC, extra_keys ASC);\n\nCREATE TABLE ops360uat01_lineage.attribute_correction (\n    object_id text,\n    attribute_id text,\n    applies_at timestamp,\n    recorded_on timestamp,\n    extra_keys text,\n    datamodel_id text,\n    class_id text,\n    lineage text,\n    lineage_addition text,\n    transaction_id text,\n    process_id text,\n    source_id bigint,\n    source_name text,\n    user_id text,\n    comment text,\n    PRIMARY KEY ((object_id, attribute_id), applies_at, recorded_on, extra_keys)\n)\nWITH CLUSTERING ORDER BY (applies_at DESC, recorded_on DESC, extra_keys ASC);\n\nCREATE TABLE ops360uat01_lineage.changes_by_time (\n    year int,\n    week int,\n    recorded_on timestamp,\n    object_id text,\n    attribute_id text,\n    applies_at timestamp,\n    extra_keys text,\n    PRIMARY KEY ((year, week), recorded_on, object_id, attribute_id, applies_at, extra_keys)\n)\nWITH CLUSTERING ORDER BY (recorded_on DESC, object_id ASC, attribute_id ASC, applies_at DESC, extra_keys ASC);\n\nCREATE TABLE ops360uat01_lineage.changes_by_object (\n    object_id text,\n    year int,\n    week int,\n    recorded_on timestamp,\n    attribute_id text,\n    applies_at timestamp,\n    extra_keys text,\n    PRIMARY KEY ((object_id, year, week), recorded_on, attribute_id, applies_at, extra_keys)\n)\nWITH CLUSTERING ORDER BY (recorded_on DESC, attribute_id ASC, applies_at DESC, extra_keys ASC);\n\nCREATE TABLE IF NOT EXISTS ops360uat01_lineage.report_config (\n    id UUID,\n    name text,\n    owner text,\n    dataset_id text,\n    attributes list<text>,\n    statuses list<int>,\n    users list<text>,\n    user_roles list<text>,\n    PRIMARY KEY (id));"

    "logger.xml" = "<configuration>\n<conversionRule conversionWord=\"coloredLevel\" converterClass=\"play.api.libs.logback.ColoredLevel\" />\n<appender name=\"FILE\" class=\"ch.qos.logback.core.FileAppender\">\n    <file>$${application.home:-.}/logs/application.log</file>\n    <encoder>\n    <pattern>%date [%level] from %logger in %thread - %message%n%xException</pattern>\n    </encoder>\n</appender>\n<appender name=\"STDOUT\" class=\"ch.qos.logback.core.ConsoleAppender\">\n    <encoder>\n    <pattern>%date %coloredLevel %logger{15} - %message%n%xException{10}</pattern>\n    </encoder>\n</appender>\n<appender name=\"ASYNCFILE\" class=\"ch.qos.logback.classic.AsyncAppender\">\n    <appender-ref ref=\"FILE\" />\n</appender>\n\n<appender name=\"ASYNCSTDOUT\" class=\"ch.qos.logback.classic.AsyncAppender\">\n    <appender-ref ref=\"STDOUT\" />\n</appender>\n\n<logger name=\"play\" level=\"INFO\" />\n<logger name=\"application\" level=\"TRACE\" />\n<logger name=\"com.ac.datalineage\" level=\"TRACE\" />\n\n<logger name=\"com.datastax.driver.core\" level=\"DEBUG\" />\n\n<!--\nTurn on slow query logging by setting this logger to DEBUG;\nset level to TRACE to also log query parameters\n-->\n<logger name=\"com.datastax.driver.core.QueryLogger.SLOW\" level=\"OFF\" />\n\n<!-- Off these ones as they are annoying, and anyway we manage configuration ourselves -->\n<logger name=\"com.avaje.ebean.config.PropertyMapLoader\" level=\"OFF\" />\n<logger name=\"com.avaje.ebeaninternal.server.core.XmlConfigLoader\" level=\"OFF\" />\n<logger name=\"com.avaje.ebeaninternal.server.lib.BackgroundThread\" level=\"OFF\" />\n<logger name=\"com.gargoylesoftware.htmlunit.javascript\" level=\"OFF\" />\n\n<root level=\"WARN\">\n    <appender-ref ref=\"ASYNCFILE\" />\n    <appender-ref ref=\"ASYNCSTDOUT\" />\n</root>\n</configuration>"
  }
}

