apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops360-core-ui
  namespace: uat01
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/server-snippet: |-
      add_header X-Request-ID $request_id;
      keepalive_timeout 70;
      underscores_in_headers on;
      proxy_http_version 1.1;
      client_max_body_size 0;
      gzip  on;
      gzip_types
        text/css
        text/javascript
        text/xml
        text/plain
        application/javascript
        application/x-javascript
        application/json;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";

    nginx.ingress.kubernetes.io/configuration-snippet: |-
      more_set_headers "Cache-Control: no-cache";
    nginx.ingress.kubernetes.io/proxy-buffer-size: "24576k"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 200M
spec:
  tls:
  - hosts: 
    - ops360uat01.acx-sandbox.net   
    secretName: ops360uat01-cert
  rules:
    - host: ops360uat01.acx-sandbox.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core-ui
                port:
                  number: 80
          - path: /*/config.json
            pathType: Prefix
            backend:
              service:
                name: core-ui
                port:
                  number: 80
          - path: /*/navigation.json
            pathType: Prefix
            backend:
              service:
                name: core-ui
                port:
                  number: 80
          - path: /issue-service
            pathType: Prefix
            backend:
              service:
                name: issue-service
                port:
                  number: 9021
          - path: /select
            pathType: Prefix
            backend:
              service:
                name: ac-select
                port:
                  number: 9000                  
          - path: /ac
            pathType: Prefix
            backend:
              service:
                name: bdms-service
                port:
                  number: 6969
